### ISSUE TITLE
FormattingException: Invalid number of plural parameters

### ISSUE THREAD

**Issue by RussKie** [axuno/SmartFormat#192]
**Smart.Format version**: 2.7.0

**Framework version**:  net5.0

This looks like a regressions from 2.0.0, which we used on net461.

On v2.0.0 the following code passed:
![image](https://user-images.githubusercontent.com/4403806/131244778-b0df34ed-7e5b-4919-8d2c-3707c6fb7305.png)
..whilst 2.7.0 is failing for the same code:
![image](https://user-images.githubusercontent.com/4403806/131244870-468797ac-a1e3-4915-996b-3f2cd99fd12a.png)

Essentially this boils down to this:
```cs
var s0 = Smart.Format(CultureInfo.GetCultureInfo("en"), "{0:Child|Children}", 10, 10);   // works
var s1 = Smart.Format(CultureInfo.GetCultureInfo("ru"), "{0:Child|Children}", 10, 10);   // fails
```

Stack trace:
```
SmartFormat.Core.Formatting.FormattingException
  HResult=0x80131500
  Message=Error parsing format string: Invalid number of plural parameters at 17
{0:Child|Children}
-----------------^
  Source=SmartFormat
  StackTrace:
   at SmartFormat.SmartFormatter.FormatError(FormatItem errorItem, Exception innerException, Int32 startIndex, FormattingInfo formattingInfo)
   at SmartFormat.SmartFormatter.Format(FormattingInfo formattingInfo)
   at SmartFormat.SmartFormatter.Format(FormatDetails formatDetails, Format format, Object current)
   at SmartFormat.SmartFormatter.Format(IFormatProvider provider, String format, Object[] args)
   at SmartFormat.Smart.Format(IFormatProvider provider, String format, Object[] args)
   at ResourceManager.TranslatedStrings.GetChildren(Int32 value) in D:\Development\gitextensions2\ResourceManager\TranslatedStrings.cs:line 96
   at ResourceManager.CommitDataRenders.TabbedHeaderRenderStyleProvider..ctor() in D:\Development\gitextensions2\ResourceManager\CommitDataRenders\TabbedHeaderRenderStyleProvider.cs:line 15
   at GitUI.CommitInfo.CommitInfoHeader..ctor() in D:\Development\gitextensions2\GitUI\CommitInfo\CommitInfoHeader.cs:line 32
   at GitUI.CommitInfo.CommitInfo.InitializeComponent() in D:\Development\gitextensions2\GitUI\CommitInfo\CommitInfo.Designer.cs:line 38
   at GitUI.CommitInfo.CommitInfo..ctor() in D:\Development\gitextensions2\GitUI\CommitInfo\CommitInfo.cs:line 93
   at GitUI.CommandsDialogs.FormBrowse.InitializeComponent() in D:\Development\gitextensions2\GitUI\CommandsDialogs\FormBrowse.Designer.cs:line 70
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands commands, String filter, ObjectId selectedId, ObjectId firstId) in D:\Development\gitextensions2\GitUI\CommandsDialogs\FormBrowse.cs:line 140
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, String filter, ObjectId selectedId, ObjectId firstId) in D:\Development\gitextensions2\GitUI\GitUICommands.cs:line 1131
   at GitUI.GitUICommands.RunBrowseCommand(IReadOnlyList`1 args) in D:\Development\gitextensions2\GitUI\GitUICommands.cs:line 1565
   at GitUI.GitUICommands.RunCommandBasedOnArgument(IReadOnlyList`1 args, IReadOnlyDictionary`2 arguments) in D:\Development\gitextensions2\GitUI\GitUICommands.cs:line 1419
   at GitUI.GitUICommands.RunCommand(IReadOnlyList`1 args) in D:\Development\gitextensions2\GitUI\GitUICommands.cs:line 1392
   at GitExtensions.Program.RunApplication() in D:\Development\gitextensions2\GitExtensions\Program.cs:line 190
   at GitExtensions.Program.Main() in D:\Development\gitextensions2\GitExtensions\Program.cs:line 93
```

**Comment by RussKie** [comment]
Looks like the behaviour was changed in https://github.com/axuno/SmartFormat/commit/c1472feb3090e4a1b6ca9307c5706107ef1d751a, and can be set back to the original by:
```cs
Smart.Default.Settings.FormatErrorAction = ErrorAction.Ignore;
```
