### ISSUE TITLE
Concurrency issues with ReflectionSource

### ISSUE THREAD

**Issue by EternalClickbait** [axuno/SmartFormat#210]
**Smart.Format version**: 3.0.0.0

**Framework version**:  net5.0 (Stride3D)

**Source code example**:
Don't have a minimal repro yet, but [my repo ](https://github.com/EternalClickbait/StrideSaber/commit/0eccacd8d5ad60d176bf7e9f0bec36ff8025b6b6) is pretty consistent. Just run it normally and it should throw consistently.

**Current Result**:
I get an `InvalidOperationException` because of concurrent access of a non-concurrent collection

**Expected result**:
The collection access is fine and works properly

**Exception details**:
*Inner exception*
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at SmartFormat.Extensions.ReflectionSource.TryEvaluateSelector(ISelectorInfo selectorInfo)
   at SmartFormat.SmartFormatter.InvokeSourceExtensions(FormattingInfo formattingInfo)
   at SmartFormat.SmartFormatter.EvaluateSelectors(FormattingInfo formattingInfo)
   at SmartFormat.SmartFormatter.Format(FormattingInfo formattingInfo)
```

*Outer exception*
```
SmartFormat.Core.Formatting.FormattingException: Error parsing format string: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct. at 21
BackgroundTask "{Name}" Id {Id} ({Progress:p0})
---------------------^
   at SmartFormat.SmartFormatter.FormatError(FormatItem errorItem, Exception innerException, Int32 startIndex, IFormattingInfo formattingInfo)
   at SmartFormat.SmartFormatter.Format(FormattingInfo formattingInfo)
   at SmartFormat.SmartFormatter.Format(FormatDetails formatDetails, Object current)
   at SmartFormat.SmartFormatter.Format(IFormatProvider provider, Format format, IList`1 args)
   at SmartFormat.SmartFormatter.Format(Format format, Object[] args)
   at StrideSaber.Diagnostics.BackgroundTask.ToString(Format format) in C:\Users\Rowan\Documents\Projects\Stride3D\StrideSaber\StrideSaber\Diagnostics\BackgroundTask.cs:line 300
   at StrideSaber.Diagnostics.BackgroundTask.ToString() in C:\Users\Rowan\Documents\Projects\Stride3D\StrideSaber\StrideSaber\Diagnostics\BackgroundTask.cs:line 286
   at Serilog.Capturing.PropertyValueConverter.CreatePropertyValue(Object value, Destructuring destructuring, Int32 depth)
   at Serilog.Capturing.PropertyValueConverter.CreatePropertyValue(Object value, Destructuring destructuring)
```

*My throwing code*:
```csharp
return Smart.Default.Format(format, this);
```

**Comment by axunonb** [comment]
Thanks - will have a look later this week.

**Comment by karljj1** [comment]
Ah we do everything on the main thread. I actually removed some of the thread stuff to improve performance on our version. Yes you will likely need some lock or concurrent dictionary.

**Comment by EternalClickbait** [comment]
> 
> 
> @EternalClickbait I agree the change would be simple, and it could indeed fix your concurrency issue (although I didn't test it yet). `ConcurrentDictionary` still has a performance penalty of 20-30% _when writing_ compared to `Dictionary` under `net5.0`. Assuming that one thread or synchronizing access is the regular use case, wouldn't it be the better solution if the caller took care of `lock`ing, like you already did?

I would agree that if it's the regular use case, but in reality I think that multithreaded code is the norm for most devs now (not to mention how a lot of C# and DotNet methods are built to support async). A concurrent dictionary would be more performant than simply `lock`ing as you said, but it's not very obvious or intuitive. Really, all I'm doing is slowing down my code so that your dictionary doesn't get written to multiple times before it has a chance to properly store the values. I would reccomend that you make the change, or at least give some option, such as a different class or some switch. Also, perhaps you should put something in the readme about it being thread-safe (or not), and add some `async` unit tests.

**Comment by axunonb** [comment]
[v3.0.0-alpha.5](https://github.com/axuno/SmartFormat/releases/tag/v3.0.0-alpha.5) is published now.
Any feedback is welcome.
@EternalClickbait Regarding this issue please make sure to set `SmartSettings.IsThreadSafeMode=true`
