### ISSUE TITLE
Unhandled exception. SmartFormat.Core.Formatting.FormattingException: Error parsing format string: No source extension could handle the selector named "now" at 2

### ISSUE THREAD

**Issue by Bluscream** [axuno/SmartFormat#351]
Hi! Thanks for reporting this bug! 

Please fill in the relevant information from this template so that we can help you best.

**Smart.Format version**: 3.2.2

**Framework version**:  (e.g. net5.0) net6

- Please provide a working source code example to reproduce the bug
https://github.com/Bluscream/battlebitapirunner-modules/blob/master/modules/Logger.cs#L118
- What is the current result?
Crash
- What is the expected result?
formatted DateTime.Now
- Please post full exception details if applicable (message, stacktrace, inner exceptions)
```
Unhandled exception. SmartFormat.Core.Formatting.FormattingException: Error parsing format string: No source extension could handle the selector named "now" at 2
[{now}] API Modules loaded
--^
   at SmartFormat.SmartFormatter.FormatError(FormatItem errorItem, Exception innerException, Int32 startIndex, IFormattingInfo formattingInfo)
   at SmartFormat.SmartFormatter.Format(FormattingInfo formattingInfo)
   at SmartFormat.SmartFormatter.Format(FormatDetails formatDetails, Format format, Object current)
   at SmartFormat.SmartFormatter.Format(IFormatProvider provider, String format, IList`1 args)
   at LoggerBattlebitModule.Logger.FormatString(String input, Object[] parms) in ./modules\Logger.cs:line 118
   at LoggerBattlebitModule.Logger.HandleEvent(LogConfigurationEntry config, Object[] parms) in ./modules\Logger.cs:line 177
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
NativeCommandExitException: Program "dotnet.exe" ended with non-zero exit code: -532462766.
```
- Did you find a workaround? yes/no
no
- Is there a version in which it worked? 
not that i know of
- Can you help us by writing an unit test?
what?

**Comment by axunonb** [comment]
The provided link is not a working code sample, as it is missing the format string and the arguments to `Smart.Format()`. Also it's unclear which extensions are in use.
